[tool.poetry]
name = "nwave"
version = "0.1.0"
description = ""
authors = ["ionite34 <dev@ionite.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
dask = "^2022.5.2"
distributed = "^2022.5.2"
SoundFile = "^0.10.3"
librosa = "^0.9.1"
samplerate = "^0.1.0"
soxr = "^0.3.0a2"
bokeh = "^2.4.3"
ffmpeg-python = "^0.2.0"
aiofiles = "^0.8.0"
atomicwrites = "^1.4.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
jupyter = "^1.0.0"
yaspin = "^2.1.0"
bokeh = "^2.4.3"
line-profiler-pycharm = "^1.1.0"
cpu-load-generator = "^1.2.0"
tqdm = "^4.64.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
